docker-build-master-local:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_LOCALREGISTRY_USER" -p "$CI_LOCALREGISTRY_TOKEN" $CI_LOCALREGISTRY
  script:
    - docker build --build-arg TARGETPLATFORM="linux/amd64" --build-arg PROJECT_VERSION="3.5.2.3" --pull -t "$CI_LOCALREGISTRY/$STABLE_IMAGE" .
    - docker push "$CI_LOCALREGISTRY/$STABLE_IMAGE"
  only:
    - master
  except:
    changes:
      - docsbyice/*

docker-build-master-dh:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" $CI_REGISTRY
  script:
    - docker build --build-arg TARGETPLATFORM="linux/amd64" --build-arg PROJECT_VERSION="3.5.2.3" --pull -t "$CI_REGISTRY/$STABLE_IMAGE" .
    - docker push "$CI_REGISTRY/$STABLE_IMAGE"
  only:
    - master
  except:
    changes:
      - docsbyice/*

docker-build-develop:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_LOCALREGISTRY_USER" -p "$CI_LOCALREGISTRY_TOKEN" $CI_LOCALREGISTRY
  script:
    - docker build --build-arg TARGETPLATFORM="linux/amd64" --build-arg PROJECT_VERSION="3.5.2.3" --pull -t "$CI_LOCALREGISTRY/$CANARY_IMAGE" .
    - docker push "$CI_LOCALREGISTRY/$CANARY_IMAGE"
  except:
    changes:
      - docsbyice/*

docker-build-tags:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_LOCALREGISTRY_USER" -p "$CI_LOCALREGISTRY_TOKEN" $CI_LOCALREGISTRY
  script:
    - docker build --build-arg TARGETPLATFORM="linux/amd64" --build-arg PROJECT_VERSION="3.5.2.3" --pull -t "$CI_LOCALREGISTRY/$TAG_IMAGE:$CI_COMMIT_TAG" .
      - docker push "$CI_LOCALREGISTRY/$TAG_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags
  except:
    changes:
      - docsbyice/*

image: python:latest
pages:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - docsbyice/*
  script:
    - pip install mkdocs-material
    - cd docsbyice
    - mkdocs build --site-dir ../public
  artifacts:
    paths:
      - public
